---
include: false
---

--------------------------------------------------------------------------------
The lab notebook is the main place to design the code, try things iteratively 
and not worry too much about the final output. It will not be rendered upon 
running `quarto render` in the terminal, because the file name begins with an
underscore.

*Workflow:*
- Write code and explore the data in the lab notebook.
- When something is functional, reproducible and ready to be included in the
  main pipeline, remodel it into a function.
- Transfer said function inside a standalone R script in the R/ folder.
- These functions will be run successively in the final analysis and reports.
--------------------------------------------------------------------------------

```{r}
#| label: setup

if (!requireNamespace("pacman")) install.packages("pacman")

pacman::p_load(
  here, 
  ggplot2
  )
```

Here is how the example functions in the R/ folder could have been initially 
tested here:

```{r}
#| label: import-iris

df <- iris
```

```{r}
#| label: tidy-iris

colnames(df) <- tolower(colnames(df))

head(df)
```

```{r}
#| label: plot-iris

p <- 
  df |> 
  ggplot(aes(
    x = sepal.length, 
    y = sepal.width, 
    color = species)
  ) +
  geom_point()

print(p)
```

```{r}
#| label: model-iris

model <- lm(
  sepal.width ~ sepal.length + petal.length + petal.width,
  data = df
)

summary(model)
```

As each step becomes functional and ready to be run a thousand times, we wrap it
in a function and externalise it.